import "@uploadthing/react/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import AuthProvider from "../context/AuthProvider";
import Navigation from "@/components/navbar/Navigation";
import ToasterProvider from "./providers/ToasterProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <ToasterProvider />
          <Navbar />
          <div className="fixed  flex justify-between top-12 h-[calc(100vh-3rem)] w-screen">
            <Navigation />

            <div className="relative flex justify-center flex-grow overflow-y-scroll">
              {children}
            </div>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
